---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/content/photographies
  label: Ajouter une photographie
  create: documents
  match: "**/*"
  templates:
  - photographies
- type: directory
  path: src/content/prestations
  label: Ajouter une prestation
  create: documents
  match: "**/*"
  templates:
  - prestations
upload_dir: dist/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
